In [2]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# importing dataset, assigning independent variable x and dependent variable y
dataset = pd.read_csv('housing.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
dataset

RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]

In [4]:
# splitting dataset into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [5]:
x_train

array([[ 6.209, 13.22 , 20.2  ],
       [ 5.427, 18.14 , 20.2  ],
       [ 5.349, 19.77 , 20.2  ],
       ...,
       [ 6.021, 10.3  , 17.8  ],
       [ 6.03 , 18.8  , 17.9  ],
       [ 6.02 , 10.11 , 16.6  ]])

In [6]:
y_train

array([ 449400.,  289800.,  174300.,  275100.,  661500.,  411600.,
        275100.,  132300.,  357000.,  483000.,  285600.,  493500.,
        701400.,  405300.,  338100.,  743400.,  682500.,  466200.,
        176400.,  373800.,  394800., 1014300.,  636300.,  228900.,
        262500.,  350700.,  567000.,  417900.,  407400.,  415800.,
        525000.,  506100.,  348600.,  474600.,  760200.,  485100.,
        602700.,  432600.,  380100.,  438900.,  430500.,  319200.,
        365400.,  285600.,  474600.,  382200.,  176400.,  312900.,
        693000.,  453600.,  560700.,  501900.,  436800.,  478800.,
        327600.,  252000.,  409500.,  432600.,  289800.,  781200.,
        653100.,  663600.,  430500.,  602700.,  455700.,  409500.,
        499800.,  409500.,  499800.,  525000.,  497700.,  281400.,
        264600., 1024800.,  602700.,  117600.,  483000.,  525000.,
        905100.,  399000.,  499800.,  214200.,  480900.,  424200.,
        289800.,  510300.,  451500.,  766500.,  510300.,  3696

In [7]:
x_test

array([[ 5.834,  8.47 , 21.   ],
       [ 6.842,  6.9  , 13.   ],
       [ 5.403, 26.82 , 14.7  ],
       [ 6.852, 19.78 , 20.2  ],
       [ 6.417,  8.81 , 17.8  ],
       [ 6.406, 19.52 , 20.2  ],
       [ 4.903, 29.29 , 14.7  ],
       [ 6.112, 12.67 , 20.2  ],
       [ 6.163, 11.34 , 18.   ],
       [ 5.965, 13.83 , 21.   ],
       [ 6.223, 21.78 , 20.2  ],
       [ 5.837, 15.69 , 20.2  ],
       [ 6.041,  7.7  , 19.6  ],
       [ 4.628, 34.37 , 20.2  ],
       [ 6.727,  9.42 , 20.9  ],
       [ 5.757, 17.31 , 21.2  ],
       [ 6.279, 11.97 , 18.7  ],
       [ 6.51 ,  7.39 , 14.7  ],
       [ 5.807, 16.03 , 18.6  ],
       [ 6.739,  4.69 , 15.2  ],
       [ 7.327, 11.25 , 13.   ],
       [ 7.135,  4.45 , 17.   ],
       [ 4.519, 36.98 , 20.2  ],
       [ 5.85 ,  8.77 , 19.2  ],
       [ 5.569, 15.1  , 19.2  ],
       [ 7.645,  3.01 , 14.9  ],
       [ 7.333,  7.79 , 13.   ],
       [ 7.61 ,  3.11 , 14.7  ],
       [ 6.395, 13.27 , 20.2  ],
       [ 6.019, 12.92 , 19.2  ],
       [ 6

In [8]:
y_test

array([417900., 632100., 281400., 577500., 474600., 359100., 247800.,
       474600., 449400., 411600., 214200., 214200., 428400., 375900.,
       577500., 327600., 420000., 489300., 470400., 640500., 651000.,
       690900., 147000., 441000., 367500., 966000., 756000., 888300.,
       455700., 445200., 323400., 455700., 430500., 867300., 445200.,
       875700., 415800., 268800., 590100., 497700., 231000., 315000.,
       388500., 449400., 413700., 352800., 453600., 306600., 898800.,
       514500., 743400., 474600., 600600., 304500., 661500., 489300.,
       422100., 184800., 525000., 249900., 407400., 361200., 428400.,
       392700., 428400., 472500., 258300., 550200., 346500., 199500.,
       302400., 611100., 396900., 585900., 279300., 483000., 462000.,
       218400., 518700., 420000., 392700., 980700., 455700., 514500.,
       480900., 520800., 485100., 525000., 390600., 569100., 359100.,
       346500., 283500., 344400., 459900., 464100., 432600., 617400.])

In [10]:
# training the model
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train, y_train)

SVR()

In [21]:
# predicting prices
y_pred = regressor.predict(x_test)
np.set_printoptions(precision = 2)
print("Predicted values are:")
print(y_pred)

Predicted values are:
[436817.4  436843.66 436703.07 436687.54 436827.87 436688.52 436712.64
 436766.   436793.75 436746.74 436679.63 436724.13 436832.34 436728.3
 436808.07 436704.54 436782.12 436844.39 436724.61 436858.07 436804.75
 436859.27 436739.65 436822.63 436734.46 436857.39 436838.02 436857.08
 436757.57 436765.89 436693.03 436742.43 436806.36 436857.3  436776.58
 436857.01 436826.61 436678.51 436818.39 436857.32 436680.14 436701.66
 436781.39 436823.21 436682.39 436737.77 436824.04 436699.34 436854.4
 436755.96 436857.75 436797.97 436852.78 436703.02 436858.13 436844.74
 436736.09 436682.81 436817.05 436823.61 436743.49 436681.32 436736.02
 436715.38 436743.58 436702.71 436680.53 436844.54 436833.36 436679.75
 436728.8  436844.35 436733.41 436853.22 436681.43 436784.34 436798.23
 436707.95 436854.15 436737.17 436760.43 436859.18 436809.2  436814.77
 436786.18 436852.84 436849.69 436845.06 436792.32 436709.15 436781.
 436713.29 436709.76 436716.15 436850.27 436850.13 436811.0

In [22]:
numrows = len(y_test)

In [23]:
# creating new dataframe to store Original_Price and Predicted_Price
regression_df = pd.DataFrame({'Original_Price':[0.0]*numrows,
                              'Predicted_Price':[0.0]*numrows})

In [24]:
seq = ['Original_Price',
       'Predicted_Price']

In [25]:
regression_df = regression_df.reindex(columns=seq)

In [26]:
for i in range(0 , numrows):
    real_values = y_test[i]
    predicted_values = y_pred[i]
    
    regression_df.iat[i,0] = real_values
    regression_df.iat[i,1] = predicted_values


regression_df = regression_df.dropna() #exclude any rows with missing data
print(regression_df)

    Original_Price  Predicted_Price
0         417900.0    436817.401624
1         632100.0    436843.659328
2         281400.0    436703.066278
3         577500.0    436687.538482
4         474600.0    436827.868452
..             ...              ...
93        344400.0    436716.154769
94        459900.0    436850.274402
95        464100.0    436850.126258
96        432600.0    436811.011070
97        617400.0    436856.949899

[98 rows x 2 columns]


In [28]:
# printing Original_Price and Predicted_Price in a new csv file
regression_df.to_csv('predict_price.csv', index = True)